name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-lint:
    name: Test Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest

      - name: Run Tests
        run: pytest

  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Log in to Amazon ECR hello-app
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: eu-west-2
          mask-password: true
          registry-type: private

      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 -t hello-app .

      - name: Tag Docker image
        run: |
          docker tag hello-app:latest 303981612052.dkr.ecr.eu-west-2.amazonaws.com/hello-app:latest

      - name: Push docker image to ECR
        run: |
          docker push 303981612052.dkr.ecr.eu-west-2.amazonaws.com/hello-app:latest

      - name: Update ECS service trigger new deployment
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service \
            --cluster ecs-cluster_test \
            --service hello-service \
            --force-new-deployment \
